eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
 microservice:
  payment-service:
    endpoints:
      endpoint:
        Uri: http://PAYMENT-SERVICE/payment/doPayment
  booking-service:
    endpoints:
      endpoint:
        Uri: http://BOOKING-SERVICE/book/bookOrder   
    
